### PR TITLE
feat: multi concat

### PR DESCRIPTION
**Pull request by juliachen-arcticleaf**
## What? Why?
Adding multiConcat handlebar helper for concatenate function which accepts more than 2 elements

## How was it tested?
create test cases that accept string, boolean, number, empty string

----

cc @bigcommerce/storefront-team

### CODE REVIEW

**Review by jairo-bc — APPROVED** [review]

**Comment by jairo-bc** [comment]
cc @bigcommerce/dev-docs

**Comment by juliachen-arcticleaf** [comment]
> LGTM 👍

Thanks, Jairo! What would be the next steps?

**Comment by jairo-bc** [comment]
@juliachen-arcticleaf We will take this version to the next release, that will happen during this week.

**Comment by juliachen-arcticleaf** [comment]
> @juliachen-arcticleaf We will take this version to the next release, that will happen during this week.
That's nice! Thanks!!

**Pull request merged**
